### PR TITLE
Add Readme to Sphinx documentation

### PR DESCRIPTION
**Pull request by crccheck**
## Why are we doing this?

If you look at the current documentation site: https://launch-vehicle-fbm.readthedocs.io/en/latest/ You'll notice the homepage is blank. This hacks a way to get the README to take that empty space.

## Did you document your work?

The Makefile has all the commands. It's not obvious that you need to build the docs if you update the README right now, but I'm hoping that future tooling will make this easier. It's sort of acceptable to let `index_readme.rst` to get out of sync right now because the tooling ain't great.

## How can someone test these changes?

Steps to manually verify the change:

1. `cd docs`
2. `make install`
3. `make build` -- index_readme.rst should get built.
4. `make watch`
5. browse to http://localhost:8000 -- you should see the README presented

## What possible risks or adverse effects are there?

* no code changes, this just makes the docs better
* we're storing generated docs in source control. That means if the README change, there's double the lines changed

## What are the follow-up tasks?

* none

It's currently not possible, but it'd be nice if the ReadTheDocs build process could do the build. That way, we could at least put `index_readme.rst` in `.gitignore`

## Are there any known issues?

none

## Did the test coverage decrease?

_(Optional)_ Test coverage: increasing test coverage is important to us. If you let test
coverage slip, you have to justify it.

### CODE REVIEW

**Comment by stripethree** [comment]
I hadn't done python on my work laptop in a while so I had to go through some things. Documenting it here just in case someone else comes along in the same situation.

```shell
# After seeing this: You are using pip version 8.1.2, however version 10.0.1 is available.
pip install --upgrade pip
# Also needed virtualenv and wrapper
pip install virtualenv
pip install virtualenvwrapper
# Need to add this to my .zshrs
source /usr/local/bin/virtualenvwrapper.sh
mkvirtualenv launch-vehicle-fbm
make install

# That gave me this though:
# Error: Xcode alone is not sufficient on Sierra.
# Install the Command Line Tools:
#  xcode-select --install

xcode-select --install
```

**Review by stripethree — CHANGES_REQUESTED** [review]
Now, for actually testing this, `make build` threw an encoding error:
```
pandoc --from=markdown --to=rst --output=index_readme.rst ../README.md
Running Sphinx v1.7.4
WARNING: the config value 'copyright' is set to a string with non-ASCII characters; this can lead to Unicode errors occurring. Please use Unicode strings, e.g. u'Content'.
WARNING: the config value 'author' is set to a string with non-ASCII characters; this can lead to Unicode errors occurring. Please use Unicode strings, e.g. u'Content'.
making output directory...
loading pickled environment... not yet created

Encoding error:
'ascii' codec can't decode byte 0xc3 in position 10: ordinal not in range(128)
The full traceback has been saved in /var/folders/ry/ppgslgsx43b1pzp9pn1xml7s3ttsz6/T/sphinx-err-HT7Cai.log, if you want to report the issue to the developers.
make: *** [html] Error 2
```

That said...
```python -V
Python 2.7.12
```
Are you using python 3 and is that potentially my problem?

**Comment by crccheck** [comment]
yup, Python 3. Python 2 reaches EOL in a year and a half. I don't even bother validating my stuff against Python 2 anymore. You can try this guide to get Python https://cnissues.atlassian.net/wiki/spaces/ENG/pages/123549741/Python (requires signin)

**Comment by crccheck** [comment]
It's pretty hard to justify the sphinx-js environment here. I'm still meh about it. The way it generates docs from the code is really nice though, and I still haven't found anything as good as Sphinx-JS. If it weren't for that, I'd find a pure JS solution.

What if I redid the documentation process to use Docker?

**Comment by crccheck** [comment]
found some more info about how ReadTheDocs does builds http://docs.readthedocs.io/en/latest/builds.html changing it seems doable, but hard

**Comment by stripethree** [comment]
Got further, but still not all the way there.

```
sphinx_rtd_theme is no longer a hard dependency since version 1.4.0. Please install it manually.(pip install sphinx_rtd_theme)
make: *** [html] Error 2
```
Add this to `requirements.txt`?

```
(launch-vehicle-fbm) ➜  docs git:(add-readme-to-sphinx) ✗ make build   
pandoc --from=markdown --to=rst --output=index_readme.rst ../README.md
Running Sphinx v1.7.4
loading pickled environment... not yet created

Sphinx error:
jsdoc was not found. Install it using "npm install -g jsdoc".
```

Add something that indicates the assumption of `jsdoc` installed globally?

```
(launch-vehicle-fbm) ➜  docs git:(add-readme-to-sphinx) ✗ make build
...
Sphinx error:
Builder name build not registered or available through entry point
make: *** [build] Error 2
```

Expected?

`make watch` runs and I can see docs on 8080.

**Pull request closed without merging**
